/**
 * Copyright IBM Corporation 2016
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

import Foundation

public enum EnrichedUrl: String {
    
    case Image = "enriched.url.image"
    case ImageKeywords = "enriched.url.imageKeywords"
    case ImageKeywordText = "enriched.url.imageKeywords.imageKeyword.text"
    case ImageKeywordScore = "enriched.url.imageKeywords.imageKeyword.score"
    case Feeds = "enriched.url.feeds"
    case Feed = "enriched.url.feeds.feed.feed"
    case Url = "enriched.url.url"
    case Title = "enriched.url.title"
    case CleanedTitle = "enriched.url.cleanedTitle"
    case Language = "enriched.url.language"
    case PublicationDate = "enriched.url.publicationDate.date"
    case PublicationDateConfidence = "enriched.url.publicationDate.confident"
    case Text = "enriched.url.text"
    case Author = "enriched.url.author"
    case Keywords = "enriched.url.keywords"
    case KeywordText = "enriched.url.keywords.keyword.text"
    case KeywordRelevance = "enriched.url.keywords.keyword.relevance"
    case KeywordSentimentType = "enriched.url.keywords.keyword.sentiment.type"
    case KeywordSentimentScore = "enriched.url.keywords.keyword.sentiment.score"
    case KeywordSentimentMixed = "enriched.url.keywords.keyword.sentiment.mixed"
    case KeywordKnowledgeGraph = "enriched.url.keywords.keyword.knowledgeGraph.typeHierarchy"
    case Entities = "enriched.url.entities"
    case EntityText = "enriched.url.entities.entity.text"
    case EntityType = "enriched.url.entities.entity.type"
    case EntityKnowledgeGraph = "enriched.url.entities.entity.knowledgeGraph.typeHierarchy"
    case EntityCount = "enriched.url.entities.entity.count"
    case EntityRelevance = "enriched.url.entities.entity.relevance"
    case EntitySentimentType = "enriched.url.entities.entity.sentiment.type"
    case EntitySentimentScore = "enriched.url.entities.entity.sentiment.score"
    case EntitySentimentMixed = "enriched.url.entities.entity.sentiment.mixed"
    case EntityDisambiguatedName = "enriched.url.entities.entity.disambiguated.name"
    case EntityDisambiguatedGeo = "enriched.url.entities.entity.disambiguated.geo"
    case EntityDisambiguatedDbpedia = "enriched.url.entities.entity.disambiguated.dbpedia"
    case EntityDisambiguatedWebsite = "enriched.url.entities.entity.disambiguated.website"
    case EntityDisambiguatedSubType = "enriched.url.entities.entity.disambiguated.subType"
    case EntityDisambiguatedSubType_ = "enriched.url.entities.entity.disambiguated.subType.subType_"
    case EntityQuotations = "enriched.url.entities.entity.quotations"
    case EntityQuotation = "enriched.url.entities.entity.quotations.quotation_.quotation"
    case EntityQuotationSentimentType = "enriched.url.entities.entity.quotations.quotation_.sentiment.type"
    case EntityQuotationSentimentScore = "enriched.url.entities.entity.quotations.quotation_.sentiment.score"
    case EntityQuotationSentimentMixed = "enriched.url.entities.entity.quotations.quotation_.sentiment.mixed"
    case Concepts = "enriched.url.concepts"
    case ConceptText = "enriched.url.concepts.concept.text"
    case ConceptRelevance = "enriched.url.concepts.concept.relevance"
    case ConceptKnowledgeGraph = "enriched.url.concepts.concept.knowledgeGraph.typeHierarchy"
    case Relations = "enriched.url.relations"
    case RelationSentence = "enriched.url.relations.relation.sentence"
    case RelationSubjectText = "enriched.url.relations.relation.subject.text"
    case RelationSubjectEntities = "enriched.url.relations.relation.subject.entities"
    case RelationSubjectEntityText = "enriched.url.relations.relation.subject.entities.entity.text"
    case RelationSubjectEntityType = "enriched.url.relations.relation.subject.entities.entity.type"
    case RelationSubjectEntityKnowledgeGraph = "enriched.url.relations.relation.subject.entities.entity.knowledgeGraph.typeHierarchy"
    case RelationSubjectEntityCount = "enriched.url.relations.relation.subject.entities.entity.count"
    case RelationSubjectEntityRelevance = "enriched.url.relations.relation.subject.entities.entity.relevance"
    case RelationSubjectEntitySentimentType = "enriched.url.relations.relation.subject.entities.entity.sentiment.type"
    case RelationSubjectEntitySentimentScore = "enriched.url.relations.relation.subject.entities.entity.sentiment.score"
    case RelationSubjectEntitySentimentMixed = "enriched.url.relations.relation.subject.entities.entity.sentiment.mixed"
    case RelationSubjectEntityDisambiguatedName = "enriched.url.relations.relation.subject.entities.entity.disambiguated.name"
    case RelationSubjectEntityDisambiguatedGeo = "enriched.url.relations.relation.subject.entities.entity.disambiguated.geo"
    case RelationSubjectEntityDisambiguatedDbpedia = "enriched.url.relations.relation.subject.entities.entity.disambiguated.dbpedia"
    case RelationSubjectEntityDisambiguatedWebsite = "enriched.url.relations.relation.subject.entities.entity.disambiguated.website"
    case RelationSubjectEntityDisambiguatedSubType = "enriched.url.relations.relation.subject.entities.entity.disambiguated.subType"
    case RelationSubjectEntityDisambiguatedSubType_ = "enriched.url.relations.relation.subject.entities.entity.disambiguated.subType.subType_"
    case RelationSubjectEntityQuotations = "enriched.url.relations.relation.subject.entities.entity.quotations"
    case RelationSubjectEntityQuotation = "enriched.url.relations.relation.subject.entities.entity.quotations.quotation_.quotation"
    case RelationSubjectEntityQuotationSentimentType = "enriched.url.relations.relation.subject.entities.entity.quotations.quotation_.sentiment.type"
    case RelationSubjectEntityQuotationSentimentScore = "enriched.url.relations.relation.subject.entities.entity.quotations.quotation_.sentiment.score"
    case RelationSubjectEntityQuotationSentimentMixed = "enriched.url.relations.relation.subject.entities.entity.quotations.quotation_.sentiment.mixed"
    case RelationSubjectKeywords = "enriched.url.relations.relation.subject.keywords"
    case RelationSubjectKeywordText = "enriched.url.relations.relation.subject.keywords.keyword.text"
    case RelationSubjectKeywordRelevance = "enriched.url.relations.relation.subject.keywords.keyword.relevance"
    case RealtionSubjectKeywordSentimentType = "enriched.url.relations.relation.subject.keywords.keyword.sentiment.type"
    case RelationSubjectKeywordSentimentScore = "enriched.url.relations.relation.subject.keywords.keyword.sentiment.score"
    case RealtionSubjectKeywordSentimentMixed = "enriched.url.relations.relation.subject.keywords.keyword.sentiment.mixed"
    case RelationSubjectKeywordKnowledgeGraph = "enriched.url.relations.relation.subject.keywords.keyword.knowledgeGraph.typeHierarchy"
    case RelationSubjectSentimentType = "enriched.url.relations.subject.sentiment.type"
    case RelationSubjectSentimentScore = "enriched.url.relations.subject.sentiment.score"
    case RelationSubjectSentimentMixed = "enriched.url.relations.subject.sentiment.mixed"
    case RelationActionText = "enriched.url.relations.relation.action.text"
    case RelationActionLemmatized = "enriched.url.relations.relation.action.lemmatized"
    case RelationActionVerbText = "enriched.url.relations.relation.action.verb.text"
    case RelationActionVerbTense = "enriched.url.relations.relation.action.verb.tense"
    case RelationActionVerbNegated = "enriched.url.relations.relation.action.verb.negated"
    case RelationObjectText = "enriched.url.relations.relation.object.text"
    case RelationObjectEntities = "enriched.url.relations.relation.object.entities"
    case RelationObjectEntityText = "enriched.url.relations.relation.object.entities.entity.text"
    case RelationObjectEntityType = "enriched.url.relations.relation.object.entities.entity.type"
    case RelationObjectEntityKnowledgeGraph = "enriched.url.relations.relation.objcet.entities.entity.knowledgeGraph.typeHierarchy"
    case RelationObjectEntityCount = "enriched.url.relations.relation.object.entities.entity.count"
    case RelationObjectEntityRelevance = "enriched.url.relations.relation.object.entities.entity.relevance"
    case RelationObjectEntitySentimentType = "enriched.url.relations.relation.object.entity.sentiment.type"
    case RelationObjectEntitySentimentScore = "enriched.url.relations.relation.object.entity.sentiment.score"
    case RelationObjectEntitySentimentMixed = "enriched.url.relations.relation.object.entity.sentiment.mixed"
    case RelationObjectEntityDisambiguatedName = "enriched.url.relations.relation.object.entity.disambiguated.name"
    case RelationObjectEntityDisambiguatedGeo = "enriched.url.relations.relation.object.entity.disambiguated.geo"
    case RelationObjectEntityDisambiguatedDbpedia = "enriched.url.relations.relation.object.entity.disambiguated.dbpedia"
    case RelationObjectEntityDisambiguatedWebsite = "enriched.url.relations.relation.object.entity.disambiguated.website"
    case RelationObjectEntityDisambiguatedSubType = "enriched.url.relations.relation.object.entity.disambiguated.subType"
    case RelationObjectEntityDisambiguatedSubType_ = "enriched.url.relations.relation.object.entity.disambiguated.subType.subType_"
    case RelationObjectEntityQuotations = "enriched.url.relations.relation.object.entity.quotations"
    case RelationObjectEntityQuotation = "enriched.url.relations.relation.object.entity.quotations.quotation_.quotation"
    case RelationObjectEntityQuotationSentimentType = "enriched.url.relations.relation.object.entity.quotations.quotation_.sentiment.type"
    case RelationObjectEntityQuotationSentimentScore = "enriched.url.relations.relation.object.entity.quotations.quotation_.sentiment.score"
    case RelationObjectEntityQuotationSentimentMixed = "enriched.url.relations.relation.object.entity.quotations.quotation_.sentiment.mixed"
    case RelationObjectKeywords = "enriched.url.relations.relation.object.keywords"
    case RelationObjectKeywordText = "enriched.url.relations.relation.object.keywords.keyword.text"
    case RelationObjectKeywordRelevance = "enriched.url.relations.relation.objcet.keywords.keyword.relevance"
    case RelationObjectKeywordSentimentType = "enriched.url.relations.relation.object.keywords.keyword.sentiment.type"
    case RelationObjectKeywordSentimentScore = "enriched.url.relations.relation.object.keywords.keyword.sentiment.score"
    case RelationObjectKeywordSentimentMixed = "enriched.url.relations.relation.object.keywords.keyword.sentiment.mixed"
    case RelationObjectKeywordKnowledgeGraph = "enriched.url.relations.relation.object.keywords.keyword.knowledgeGraph.typeHierarchy"
    case RelationObjectSentimentType = "enriched.url.relations.relation.object.sentiment.type"
    case RelationObjectSentimentScore = "enriched.url.relations.relation.object.sentiment.score"
    case RelationObjectSentimentMixed = "enriched.url.relations.relation.object.sentiment.mixed"
}